# Generated by Django 5.2.6 on 2025-10-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_survey_program_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='program_study',
        ),
    ]
