# Generated by Django 5.2.6 on 2025-11-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSpecificQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('radio', 'Single Choice'), ('checkbox', 'Multiple Choice'), ('scale', 'Scale 1–5'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.programstudy')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_questions', to='api.survey')),
            ],
        ),
    ]
