# Generated by Django 5.2.6 on 2025-11-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstudy',
            name='faculty',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='programstudy',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.department'),
        ),
    ]
