# Generated by Django 5.2.6 on 2025-11-26 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_programstudy_faculty_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=255)),
                ('next_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.question')),
            ],
        ),
    ]
