# Generated by Django 5.2.6 on 2025-09-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_address_user_fullname_user_last_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
    ]
