# Generated by Django 5.2.6 on 2025-11-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username'),
        ('api', '0006_programspecificquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='program_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.programstudy'),
        ),
    ]
