# Generated by Django 5.2.6 on 2025-11-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_program_study'),
        ('api', '0006_programspecificquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.programstudy'),
        ),
    ]
