# Generated by Django 5.2.6 on 2025-11-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_program_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
