# Generated by Django 5.2.6 on 2025-11-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_nim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nim',
        ),
    ]
